Default: &defaults
  user: fun
  password: funfun
  port: 5432
  host: 127.0.0.1
  database: fun
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Fun_test
  <<: *defaults

Staging:
  database: Fun_staging
  poolsize: 100
  <<: *defaults

Production:
  database: Fun_production
  poolsize: 100
  <<: *defaults
